"""Content service package."""

from app.services.content.core import (
    audit_content,
    create_content,
    create_content_batch,
    delete_content,
    edit_content_metadata,
    get_content,
    get_content_orm,
    increment_download_count,
    increment_view_count,
    list_contents,
    mark_content_ai_failed,
    mark_content_ai_processing,
    reindex_content_search,
    render_group_approved_markdown,
    send_file_to_user,
    update_content,
    update_content_ai_fields,
    update_content_media_dimensions,
)
from app.services.content.errors import (
    ContentForbiddenError,
    ContentNotFoundError,
    InvalidAuditActionError,
    InvalidCategoryError,
    raise_content_error,
)
from app.services.content.hot_score import (
    calculate_hot_score,
    update_all_hot_scores,
    update_hot_score,
)

__all__ = [
    "audit_content",
    "calculate_hot_score",
    "create_content",
    "create_content_batch",
    "delete_content",
    "edit_content_metadata",
    "get_content",
    "get_content_orm",
    "increment_download_count",
    "increment_view_count",
    "list_contents",
    "mark_content_ai_failed",
    "mark_content_ai_processing",
    "reindex_content_search",
    "render_group_approved_markdown",
    "send_file_to_user",
    "update_all_hot_scores",
    "update_content",
    "update_content_ai_fields",
    "update_content_media_dimensions",
    "update_hot_score",
    "ContentForbiddenError",
    "ContentNotFoundError",
    "InvalidAuditActionError",
    "InvalidCategoryError",
    "raise_content_error",
]
